spring.application.name=SupplyFlow1
spring.datasource.url=jdbc:mysql://localhost:3306/supplyflow
spring.datasource.username=root
spring.datasource.password=

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect

# H2 console (optional)
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console
